ci:
  autofix_commit_msg: "style: apply pre-commit fixes"
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
